version: '3'
services:
  racktables:
    image: "cent7-glpi:9.3.0"
    restart: always
    container_name: glpi
    hostname: glpi
    domainname: prosethsolutions.lab
    network_mode: bridge
    ports:
      - 8082:80
    volumes:
      - /srv/docker-data/glpi:/var/www/html
